name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Upgrade and Deploy
        run: |
          # Go to project folder
          cd /root/uruti-saluni/urutiSaluni
          
          # Pull latest code (to get deploy.sh)
          git pull origin master
          
          # Ensure script is executable
          chmod +x deploy.sh
          
          # Run the deployment script
          ./deploy.sh
